name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache node modules
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Check Backend Setup
      run: |
        if [ ! -f "backend/package.json" ]; then
          echo "Error: backend/package.json not found"
          exit 1
        fi

    - name: Install and Check Backend
      run: |
        cd backend
        npm install
        npm test -- --passWithNoTests || true
        npm run lint || true

    - name: Check Frontend Setup
      run: |
        if [ ! -f "frontend/package.json" ]; then
          echo "Error: frontend/package.json not found"
          exit 1
        fi

    - name: Install and Check Frontend
      run: |
        cd frontend
        npm install
        npm test -- --passWithNoTests || true
        npm run lint || true

    - name: Build Backend
      run: |
        cd backend
        npm run build

    - name: Build Frontend
      run: |
        cd frontend
        npm run build

    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        echo "Add your deployment commands here"
        # Example:
        # - For Vercel: npx vercel --prod
        # - For Heroku: heroku container:push web -a your-app-name 
